### PR TITLE
responses is a development-only dependency

### PR DESCRIPTION
**Pull request by asottile-sentry**

### CODE REVIEW

**Comment by asottile-sentry** [comment]
the failures here aren't my change -- your workflow is broken for external contributors who will not have access to CODECOV_TOKEN: https://github.com/codecov/codecov-cli/blob/f3827b3ed915f689c425b8d3986b28835973318f/.github/workflows/ci.yml#L46

**Comment by joseph-sentry** [comment]
sorry about that, that issue should be fixed now, can you try re-running the CI?

**Comment by asottile-sentry** [comment]
I do not have permission to this repository

**Review by joseph-sentry — APPROVED** [review]

**Comment by asottile-sentry** [comment]
@joseph-sentry anything left to do here?

**Comment by joseph-sentry** [comment]
I think you have to sign your commits.

Retroactively signing commits: https://stackoverflow.com/a/73367330

**Comment by asottile-sentry** [comment]
why they're thrown away at merge anyway because this repo does squash

**Comment by joseph-sentry** [comment]
good point, i'll double check with @trent-codecov about the necessity of requiring signed commits, but atm i don't have the ability to change the settings for requiring commits to be signed

**Comment by asottile-sentry** [comment]
sentry's standard does not require signing -- I'd encourage codecov to remove the unnecessary friction to contribution as well 👍

**Pull request closed without merging**
